### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8889/xxl-job-admin
    accessToken:
    executor:
      appname: sys-sync-executor
      address:
      ip:
      port: 9998
      logpath: ~/applogs/xxl-job/jobhandler
      logretentiondays: 30